GS-021 Update paths and logo
fgarcia0x0/GreenSteam pull request #6
Opened 2023-06-21 02:38 UTC by BryanProg

2023-06-21 02:48 UTC, larasous submitted a review, later dismissed

2023-06-21 02:51 UTC, fgarcia0x0 submitted a review, later dismissed

2023-06-21 03:47 UTC, larasous submitted a review, later dismissed

2023-06-21 03:59 UTC, fgarcia0x0 submitted a review, later dismissed

2023-06-21 04:04 UTC, fgarcia0x0 requested changes

2023-06-21 04:04 UTC, fgarcia0x0 commented on games.html
porque está alterando a cor do icone? Toda alteração de cor tem que ser feita pelo css

2023-06-21 04:04 UTC, fgarcia0x0 commented on index.html
porque está alterando a cor do icone? Toda alteração de cor tem que ser feita pelo css

2023-06-22 02:25 UTC, fgarcia0x0 approved these changes

2023-06-22 02:26 UTC, larasous approved these changes

2023-06-22 02:27 UTC, merged